---
- name: Tell apt to prioritize nvidia packages over all else
  become: yes
  become_user: root
  copy: src=60nvidia
        dest=/etc/apt/preferences.d/60nvidia
        owner=root
        group=root
        mode=0644

- name: "Download CUDA repo .deb package"
  get_url: "dest=/tmp/cuda-repo-ubuntu1404_7.5-18_amd64.deb url=http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64/cuda-repo-ubuntu1404_7.5-18_amd64.deb"

- name: Install CUDA repo .deb package
  apt: "deb=/tmp/cuda-repo-ubuntu1404_7.5-18_amd64.deb state=present"
  become: yes
  become_user: root

- name: Update APT cache
  apt: update_cache=yes
  become: yes
  become_user: root

- name: Install CUDA 7.5 (includes NVIDIA drivers)
  apt: pkg=cuda-7-5
       state=present
       cache_valid_time=600
  become: yes
  become_user: root
  notify:
      - Reboot server
      - Wait for server to restart

# Force handlers to run, which will cause a reboot here if one is to be performed
- meta: flush_handlers

- name: Install linux-image-extra
  apt: pkg=linux-image-extra-virtual
  become: yes
  become_user: root

- name: Test nvidia-smi
  command: nvidia-smi
