---
- name: Add ubuntu graphics-drivers ppa
  apt_repository: repo="ppa:graphics-drivers/ppa"
  become: yes
  become_user: root

- name: Add long-lived Nvidia drivers
  apt: pkg=nvidia-375 state=present update_cache=yes
  become: yes
  become_user: root
  notify:
      - Reboot server
      - Wait for server to restart

# Force handlers to run, which will cause a reboot here if one is to be performed
- meta: flush_handlers

- name: Test nvidia-smi
  command: nvidia-smi
