---
- name: Tell apt to prioritize nvidia packages over all else
  become: yes
  become_user: root
  copy: src=60nvidia
        dest=/etc/apt/preferences.d/60nvidia
        owner=root
        group=root
        mode=0644

- name: Add kernel dev and gcc packages
  apt: pkg=kernel-devel gcc state=present update_cache=yes
  become: yes
  become_user: root

- name: Download nvidia drivers
  get_url: "dest=/tmp/nv.run url=http://us.download.nvidia.com/XFree86/Linux-x86_64/367.57/NVIDIA-Linux-x86_64-367.57.run"

- name: Install nvidia drivers
  command: sh /tmp/nv.run -s
  become: yes
  become_user: root
  notify:
      - Reboot server
      - Wait for server to restart

# Force handlers to run, which will cause a reboot here if one is to be performed
- meta: flush_handlers

- name: Install linux-image-extra
  apt: pkg=linux-image-extra-virtual
  become: yes
  become_user: root

- name: Test nvidia-smi
  command: nvidia-smi
