---
- name: Add kernel dev and gcc packages
  apt: pkg={{ item }} state=present update_cache=yes
  become: yes
  become_user: root
  with_items:
      - kernel-devel
      - gcc

- name: Download nvidia drivers
  get_url: "dest=/tmp/nv.run url=http://us.download.nvidia.com/XFree86/Linux-x86_64/367.57/NVIDIA-Linux-x86_64-367.57.run"

- name: Install nvidia drivers
  command: sh /tmp/nv.run -s
  become: yes
  become_user: root
  notify:
      - Reboot server
      - Wait for server to restart

# Force handlers to run, which will cause a reboot here if one is to be performed
- meta: flush_handlers

- name: Install linux-image-extra
  apt: pkg=linux-image-extra-virtual
  become: yes
  become_user: root

- name: Test nvidia-smi
  command: nvidia-smi
