---
- name: Reboot server
  shell: nohup bash -c "sleep 2 && reboot" &
  become: yes
  become_user: root
  async: 0
  poll: 0
  ignore_errors: true

- name: Wait for server to restart
  local_action: wait_for host={{ inventory_hostname }}
                state=started
                delay=60
