---
- name: Get the latest release of nvidia-docker
  get_url: "dest=/tmp/nvidia-docker.rpm url=https://github.com/NVIDIA/nvidia-docker/releases/download/v1.0.1/nvidia-docker-1.0.1-1.x86_64.rpm"

- name: Install nvidia-docker
  command: rpm -i /tmp/nvidia-docker.rpm
  become: yes
  become_user: root

- name: Run nvidia-docker at boot
  become: yes
  become_user: root
  command: chkconfig nvidia-docker on
  notify:
    - Reboot server
    - Wait for server to restart

- meta: flush_handlers

- name: Run the cljs test
  command: nvidia-docker run --rm graphistry/cljs:1.1 npm test
