---
- name: Get the latest release of nvidia-docker
  get_url: "dest=/tmp/nvidia-docker.deb url=https://github.com/NVIDIA/nvidia-docker/releases/download/v1.0.0-rc.3/nvidia-docker_1.0.0.rc.3-1_amd64.deb"

- name: Install nvidia-docker
  command: dpkg -i /tmp/nvidia-docker.deb
  become: yes
  become_user: root

- name: Run the cljs test
  command: nvidia-docker run graphistry/cljs:1.1 npm test
