---
- name: Ensure OS is up to date
  become: yes
  become_user: root
  apt: update_cache=yes upgrade=dist

- name: Use HTTPS apt repositories
  become: yes
  become_user: root
  apt: update_cache=yes name={{ item }}
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: Add Docker GPG key
  become: yes
  become_user: root
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg state=present

- name: Create a list file for Docker
  become: yes
  become_user: root
  apt_repository: repo="deb https://download.docker.com/linux/ubuntu ubuntu-xenial main"

- name: Install Docker
  become: yes
  become_user: root
  apt: update_cache=yes name={{ item }}
  with_items:
    - linux-image-generic-lts-xenial
    - linux-headers-generic-lts-xenial
    - apparmor
    - docker-engine

- name: Start the docker daemon
  become: yes
  become_user: root
  service: name=docker state=started

- name: Verify docker is installed correctly
  become: yes
  become_user: root
  command: docker run hello-world

- name: Run docker as nonroot
  become: yes
  become_user: root
  command: usermod -aG docker {{ ansible_ssh_user }}
