---
- name: "Disable nouveau"
  copy: content="blacklist nouveau" dest=/etc/modprobe.d/blacklist.conf
  become: yes
  become_user: root

- name: "Generate initramfs image"
  command: sh -c 'dracut --force -v /boot/initramfs-$(uname -r).img $(uname -r)'
  become: yes
  become_user: root
  notify:
    - Reboot server
    - Wait for server to restart

- meta: flush_handlers

- name: "Add kernel dev packages"
  command: yum install -y kernel-devel
  become: yes
  become_user: root

- name: "Download nvidia drivers"
  get_url: "dest=/tmp/nv.run url=http://us.download.nvidia.com/XFree86/Linux-x86_64/367.57/NVIDIA-Linux-x86_64-367.57.run"

- name: "Install nvidia drivers"
  command: sh /tmp/nv.run -s
  become: yes
  become_user: root
  notify:
      - Reboot server
      - Wait for server to restart

- meta: flush_handlers

- name: Test nvidia-smi
  command: nvidia-smi
